# .github-ci.yml file

name: Github actions demo
run-name: Test ${{github.ref_name}} sur ${{ github.event.workflow_run.head_commit.message }} par ${{github.actor}}

on: push

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: define cache dir & use it npm!
        run: npm ci --cache .npm --prefer-offline
      - name: validate
        run: npm run lint
      - name: test
        run: npm test
